{{- if  .Values.auth.oauth2.clientSecret.value }}
kind: Secret
metadata:
  name: {{ include "inception.secret.oauth2.name" . }}
type: Opaque
apiVersion: v1
data:
  clientSecret: {{ required "You must specify an OIDC client secret in the 'auth.oauth2.clientSecret.value' key of your values file if you're not refereing to an existing Secret!" .Values.auth.oauth2.clientSecret.value | b64enc | quote }}
{{- end }}